// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHlC0VzCxn9cOfl9bHNBvM4x4BAE6XajY',
    appId: '1:700220144942:web:b42731a6ca1bc690e68ebf',
    messagingSenderId: '700220144942',
    projectId: 'finalproject-f1fe2',
    authDomain: 'finalproject-f1fe2.firebaseapp.com',
    storageBucket: 'finalproject-f1fe2.firebasestorage.app',
    measurementId: 'G-7M2B7Z8HRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBglXm4x2kR7CqhoVO7sGDrYaKY9UsMwoc',
    appId: '1:700220144942:android:eb3cebeebe57688ce68ebf',
    messagingSenderId: '700220144942',
    projectId: 'finalproject-f1fe2',
    storageBucket: 'finalproject-f1fe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGAE2UGhwR8sJF2BN-FeSvRrvDBqLcIJk',
    appId: '1:700220144942:ios:3d8ceb6471a1f853e68ebf',
    messagingSenderId: '700220144942',
    projectId: 'finalproject-f1fe2',
    storageBucket: 'finalproject-f1fe2.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );
}
